services:
  - type: web
    name: defit-app
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    branch: main
    autoDeploy: true
    envVars:
      - key: INFERENCE_ENGINE
        value: mock
      - key: MONGODB_DB_NAME
        value: defit
      - key: MONGODB_URL
        sync: false
